require "__X-Logistics__/prototypes/greenhouse"
require "__X-Logistics__/prototypes/recipe"
require "__X-Logistics__/prototypes/shallow-water"
require "__X-Logistics__/prototypes/landfill"
require "__X-Logistics__/prototypes/crating-machine"
require "__X-Logistics__/prototypes/map-gen-presets"